### ISSUE TITLE
Simulation freezes blender. Probably takes lots of memory.

### ISSUE THREAD

**Issue by Harvie** [vilemduha/blendercam#102]
I created simple cube cutout toolpath. It was generated in few seconds. Then i clicked on "simulate operation". Progress was quite fast, but at 100% it started to eat lots of memory and crashed whole blender. (at least i think, because ssd harddrive led was constantly glowing which is usualy caused by heavy swapping). This probably lead to OOM killing the blender by SIGKILL.

Output in terminal was like follows:

```
progress{simulation 0.0%}
progress{simulation 1.0%}
...
progress{simulation 97.0%}
progress{simulation 98.0%}
progress{simulation 99.0%}
numpy to image _Operation_1_sim.exr
7601 7601
Zabit (SIGKILL)
```
dmesg:

```
[312187.278151] Out of memory: Kill process 21518 (blender) score 462 or sacrifice child
[312187.278180] Killed process 21518 (blender) total-vm:9464024kB, anon-rss:5975168kB, file-rss:0kB, shmem-rss:4488kB
[312187.837170] oom_reaper: reaped process 21518 (blender), now anon-rss:4kB, file-rss:0kB, shmem-rss:4552kB
```

I just wanted to try the simulation, but i dont really understand what it does and how. What should i expect? What is the generated exr file?

**Comment by ksuprynowicz** [comment]
Maybe simulation resolution is too high? Try lowering it. The EXR file represents depth map of simulation.
If you want a very accurate, voxel based (can detect undercuts), open source CAM simulation software, try CAMotics:
http://camotics.org/
