### ISSUE TITLE
bas relief - image source not working

### ISSUE THREAD

**Issue by pppalain** [vilemduha/blendercam#110]
this was tried on blender 2.76.3 windows
2.77 windows
2.76 linux

Setting up image source and image target in bas relief, clicking image source opens a sort of selection pane but without anything listed
![image](https://user-images.githubusercontent.com/33393909/36447951-53710a84-165c-11e8-842d-aca006e09679.png)
![image](https://user-images.githubusercontent.com/33393909/36447990-778140c4-165c-11e8-8141-654bea839fb0.png)

typing a filename and pressing enter does not work for image source, it works for image target.

**Comment by pppalain** [comment]
anyone? hello?? is this project abandoned?

**Comment by bostjannagode** [comment]
Well, im not programmer,
 im using Blendercam sucessfully for year and more. It's working as is working, for me is ok... I was struggling with  Bas relief, but on end i suceeded...
If you want to use image as z-depth source in Bas relief, you must first open image in UV-Image editor, so it can be used in Blender internally...

Best and good work,
Bostjan

![bas](https://user-images.githubusercontent.com/15731537/38174166-8e327c2a-35c9-11e8-9c6d-d4532e8f1486.JPG)

**Comment by pppalain** [comment]
![skull screen capture](https://user-images.githubusercontent.com/33393909/38176432-28b6e1dc-35c5-11e8-8acb-0b2d6ee7871f.jpg)
That was my missing link - loading the image in UV editor.  Not an obvious step.  Thank you so much.

**Comment by bostjannagode** [comment]
pppAlain,
it was my pleasure. 
Now i need one. What were your parameters with addon that you got that result? Somehow i dont get proper image out of there. Or even no displacement....
Thanks in advance,
Bostjan
![slika](https://user-images.githubusercontent.com/15731537/55277619-a385b680-5302-11e9-8978-f707bbf32c79.png)

**Comment by pppalain** [comment]
basrelief was rewritten to automatically make the bumped plane.  an example bas relief blend file can be found.
