### ISSUE TITLE
unwanted Z-axis movements

### ISSUE THREAD

**Issue by lucky62** [vilemduha/blendercam#111]
Hello,
I am trying to mill small ornament. Generated toolpath have many unwanted Z-axis movements (returns to start Z-position). Some optimization will be good (project attached).

![image](https://user-images.githubusercontent.com/16965519/40282364-9a7be3ec-5c6e-11e8-86d7-49a6139a58f7.png)

Seems that it is dependent on some settings because the Fin is OK (only Rough is "deffective").

![image](https://user-images.githubusercontent.com/16965519/40282448-bb6a9174-5c6f-11e8-86d5-ded964cb9592.png)

[test.zip](https://github.com/vilemduha/blendercam/files/2020573/test.zip)

**Comment by ksuprynowicz** [comment]
Hi!
This is a bug concerning 'Block' operation. When you set movement type to 'meander', cutter lifting should be avoided. Can you try changing operation to 'parallel'? It seems to work perfectly for me this way.
The best strategy for such decorations is in my opinion:
1. rough parallel operation (add 0.2-0.4 mm to real cutter diameter for this to leave some material for finishing operations)
2. finishing waterlines (enabling OpenCAMLib is absolute must for this)
3. finishing parallel 0 deg.
4. finishing parallel 90 deg.

Here's manual for installing OpenCAMLib:
https://github.com/vilemduha/blendercam/wiki/Using-BlenderCAM-with-OpenCAMLib
