### ISSUE TITLE
Install steps "Scene" missing

### ISSUE THREAD

**Issue by FPChris** [vilemduha/blendercam#113]
"Enable Blendercam add-on" refers to a "Scene" category that is not there. I'm stuck.

https://github.com/vilemduha/blendercam/wiki/Using-Blendercam-from-github

**Comment by ksuprynowicz** [comment]
What Blender version are you using?

**Comment by FPChris** [comment]
The latest one on the official site. I'm not at home at the moment but I can verify later.

**Comment by FPChris** [comment]
2.79b on Windows 7 64-bit

**Comment by ksuprynowicz** [comment]
Can you run Blender from command line and post the output here? I think that it's the problem with dependencies.

**Comment by TurBoss** [comment]
i made a pack with blendercam requirements see #118

**Comment by pppalain** [comment]
irrelevant blender 2.79 no longer supported
