### ISSUE TITLE
Windows install, position object

### ISSUE THREAD

**Issue by kenpoh01** [vilemduha/blendercam#114]
Hello,
Brand new to Blender CAM.  I'm a teacher and we have a Haas TM-1 at school that nobody uses since that teacher retired.  We're trying to figure out how to use it.  I've been watching the tutorials on the blogspot site and have progressed a lot in my understanding of the software.  However I have some questions.  When setting up a job, the tutorial says to place the object in the "box" representing the work area.  It then says to press the position object button to have it positioned automatically.  When I first place the object in the box then click the button, the object jumps to the center of the x y z axis instead.
First image:
![magic_001](https://user-images.githubusercontent.com/36082436/51067495-e1ffb500-15e0-11e9-8075-a0468c57c584.jpg)
After pressing "Position Object"
![magic_002](https://user-images.githubusercontent.com/36082436/51067512-0491ce00-15e1-11e9-8462-17279eea633e.jpg)

Also, when I try to "simulate operation", I only get a small section of the part , not the whole thing.

**Comment by kenpoh01** [comment]
Any help would be appreciated.  Thanks in advance.

**Comment by ksuprynowicz** [comment]
Hi!
I've just made a simple step-by-step tutorial:
https://github.com/vilemduha/blendercam/wiki/Step-by-step-tutorial
Let me know if it works for you.
