### ISSUE TITLE
Can't read EXR from simulation, but there's a workaround??

### ISSUE THREAD

**Issue by Precognist** [vilemduha/blendercam#128]
I'm having this issue but found this workaround.
https://groups.google.com/forum/#!topic/blender-cam-forum/WWZnyi8pY-g
Saving and reopening lets me view the simulation, but any way to change this? where's it at in the python?

**Comment by Precognist** [comment]
Is it possible the getCachePath method [ops.py 918] returns null because it was empty at init and isn't recalled to see the .exr file that's added?

**Comment by ksuprynowicz** [comment]
Are you using the 2.8 branch or 2.79?

**Comment by Precognist** [comment]
Blender 2.8, Windows 10

**Comment by ksuprynowicz** [comment]
Can you upload a simple example where this occurs? I'd have a look at it them.

**Comment by Precognist** [comment]
It's fine. Save and restart works for now. Unless it's an issue for others or becomes trouble, I'll call this closed. I need help with another area.
