### ISSUE TITLE
How to add a post processor?

### ISSUE THREAD

**Issue by Precognist** [vilemduha/blendercam#129]
I'm trying to add a postprocessor that's not on the list. How do i do that? https://cam.autodesk.com/hsmposts?p=maslowcnc&_ga=2.257633419.1265823667.1571511427-1551755240.1571511427

**Comment by Precognist** [comment]
I've found the files that act as the preprocessor settings, but they are .py files. Is there a convention for converting these? Sorry to ask so much, but the topic on the board is tapped out. (2015) https://groups.google.com/forum/embed/?place=forum%2Fblender-cam-forum#!category-topic/blender-cam-forum/development/g3Hf3lnt-6E
Blender-cam is an amazing addon and I'm having the best time using it to minimize my prototyping time!

**Comment by TurBoss** [comment]
check this commits

https://github.com/vilemduha/blendercam/pull/122/files

**Comment by Precognist** [comment]
Excellent. Thank you.
