### ISSUE TITLE
G-code generation inconsistency

### ISSUE THREAD

**Issue by jmpocheau** [vilemduha/blendercam#133]
Hi,
First, let me congratulate you for this brilliant program.
Anyway, I think I found some kind of inconsistency.
I designed an object with Blender 2.80 and generated the tool path successfully.
Then, I mirrored this object and tried to generate the tool path, but this time, it didn't worked as planned and the result is a full removal of the entire object.
I attached the two images of the results : The first one is the successful tool path, the second is the failed one.
The main parameters are : parallel strategy, post-processing : grbl
I also attached the Blender file as a zip file.
Thanks in advance.
Jean-Marc

[TestCam.zip](https://github.com/vilemduha/blendercam/files/3955281/TestCam.zip)
![RightToolPath](https://user-images.githubusercontent.com/46762963/70705207-e55d5e00-1cd3-11ea-845d-780ea4f35b21.png)
![LeftToolPath](https://user-images.githubusercontent.com/46762963/70705219-ebebd580-1cd3-11ea-9b4c-8aa4729261fe.png)

**Comment by TurBoss** [comment]
hello!

the random z moves is a know bug
and for what I can see about the mirror part is that is not visible when calculated
if not check to apply all transforms ( ctrl + a) and check face directions with mesh normal recalculate outsides in edit mode with all selected

**Comment by pppalain** [comment]
newer versions of blender (3.14) have better collision and as far as we know, the random z has been fixed in the collision functions of blender.
