### ISSUE TITLE
What i doing worng ? KeyError: 'bpy_prop_collection[key]: key "" not found'

### ISSUE THREAD

**Issue by svsdval** [vilemduha/blendercam#140]
`Traceback (most recent call last):
  File "/home/svsdval/soft/blendercam/scripts/addons/cam/ops.py", line 234, in execute
    utils.getPath(context, o)
  File "/home/svsdval/soft/blendercam/scripts/addons/cam/utils.py", line 3432, in getPath
    chd = getChangeData(operation)
  File "/home/svsdval/soft/blendercam/scripts/addons/cam/utils.py", line 239, in getChangeData
    obs = [bpy.data.objects[o.object_name]]
KeyError: 'bpy_prop_collection[key]: key "" not found'

location: <unknown location>:-1
[test.zip](https://github.com/vilemduha/blendercam/files/4199566/test.zip)

`

**Comment by ksuprynowicz** [comment]
The Carve operation needs to have two sources set: curve source that will be carved and object source on which carving will be done.

![carve](https://user-images.githubusercontent.com/11568651/74459964-709dd000-4e8c-11ea-994e-825687e7c80c.jpg)

Let me know if it works for you.
If you want to machine whole surface instead, look at the Parallel operation.

**Comment by svsdval** [comment]
Thanks
