### ISSUE TITLE
I want to get the G-code of the surface of this file.

### ISSUE THREAD

**Issue by mir132** [vilemduha/blendercam#147]
![캡처](https://user-images.githubusercontent.com/65271457/81772837-d51b0a80-9521-11ea-9dfc-a6399ef4a9f5.JPG)

I have a 2D surface stl with curvature. Is there a way to G-code the path of a 2D surface?

**Comment by ksuprynowicz** [comment]
Sure!
If you want the cutter to move along curve projected on a surface, use Carve operation. You will have to create a curve (It can even be a text if you want to engrave stuff on curved surfaces). If you just want to machine the surface in the screenshot, use Parallel operation with option "cutter stays in ambient limits". "use limit curve" may also help to constrain trajectory.
