### ISSUE TITLE
I need help.(G-code)

### ISSUE THREAD

**Issue by mir132** [vilemduha/blendercam#150]
I have this file. 
It is not a simple 2D object.
 I want to draw its surface outline and get a path to fill the inside. 
How can I do this?
I want to get the path as shown in the picture.

![캡처](https://user-images.githubusercontent.com/65271457/81908495-4206d100-9604-11ea-802e-077fd5c89a1b.JPG)

![image](https://user-images.githubusercontent.com/65271457/81908345-11bf3280-9604-11ea-9b20-0dea2760dd98.png)
![제목 없음asd](https://user-images.githubusercontent.com/65271457/81908360-1683e680-9604-11ea-990a-3f3383e399e1.png)

**Comment by ksuprynowicz** [comment]
Use Parallel operation. You can set the angle of paths with "Angle of paths" option.
To limit cutter movement like you shown above you select "Around" in the option "Ambient". If you want to keep the cutter completely inside, use option "Cutter stays in ambient limits".
Let me know if it works for you.

**Comment by mir132** [comment]
@ksuprynowicz 
![image](https://user-images.githubusercontent.com/65271457/82022214-3defb780-96c7-11ea-9e01-d0051fa84d82.png)

![image](https://user-images.githubusercontent.com/65271457/82021648-295eef80-96c6-11ea-9ce5-7de382e15bcc.png)
Thanks for your answer. I ran the 2.76 blender downloaded from the Google driver. And only the sample file downloadable from the homepage could get the path of the surface. However, I couldn't get the path by creating a new page in Blender. What options or settings should I add? I am currently using window10. I want to use 2.76blender if possible.

**Comment by ksuprynowicz** [comment]
The version you want to use is already 4 years old. I advise against using it because lots of problems were fixed in between. You can try selecting "Cam" as renderer and switching on "Use exact mode", if there's such option in that release.
