### ISSUE TITLE
I want to install BLENDERCAM on Blender 2.79. It is installed by WINDOWPC. and  an error occurs when the stl file is loaded and proceeds without opening the sample file. 

### ISSUE THREAD

**Issue by mir132** [vilemduha/blendercam#151]
I want to install BLENDERCAM on Blender 2.79. It is installed by WINDOWPC.
I want to know the detailed method.
And when working with Blender 2.76 downloaded from Blender Google Drive, when the sample file is opened and an arbitrary stl file is loaded, the work proceeds. However, an error occurs when the stl file is loaded and proceeds without opening the sample file. I want to know what the reason is.
Please answer.
Thank you.

**Comment by ksuprynowicz** [comment]
Blender 2.79 is not supported anymore, and that 2.76 downloadable distribution is very outdated.
You should download Blender 2.82a and install Blendercam as described:
https://github.com/vilemduha/blendercam/wiki/Using-Blendercam-from-github

**Comment by mir132** [comment]
@ksuprynowicz 
![image](https://user-images.githubusercontent.com/65271457/82168401-a45c1c00-98f9-11ea-888d-d76e42b19217.png)
![image](https://user-images.githubusercontent.com/65271457/82168411-aa51fd00-98f9-11ea-982b-1be3627584fa.png)
I am not sure why it is not installed.
I want a solution.

**Comment by ksuprynowicz** [comment]
Shapely is not available because you are installing it on system python installation.
Each Blender version has it's own bundled python installation, so in the command line you have to go to your blender installation directory (using cd command), then to directory with bundled Python - "2.82/python/bin/",
and then execute that version of python:
https://github.com/vilemduha/blendercam/wiki/Using-Blendercam-from-github
You also should use Blender 2.82a - current version will not work with 2.79 at all due to Blender API changes.
Let me know if this works for you.

**Comment by mir132** [comment]
Thanks for the answer.
I'm going to try applying it to the 2.82a blender.
After saving the Blender file, I was able to proceed. Thank you.
I have a question.
I want to move the worktable to the target and execute the work.
In other words, I want to proceed without changing the location of the stl file and maintaining the original coordinates.
As shown in the picture, the file I want is far from the workbench.
I want to follow the coordinates of the stl file. If you move the position of stl it will break it.
![image](https://user-images.githubusercontent.com/65271457/82179103-7a662200-9918-11ea-9dea-79a90ff39aac.png)

I am very grateful for each kind answer. Thank you.

**Comment by ksuprynowicz** [comment]
You're welcome!
To preserve original coordinates you should put 3d cursor at world origin, import STL, change pivot point to 3d cursor (this is very important, otherwise model will move and coordinates won't match), and scale imported model by 1/1000 if it is in millimetre unit scale.
When you run the gcode on CNC machine, you should first do a test run with coordinate system placed a bit higher, so you won't ruin the workpiece if something went wrong.

**Comment by mir132** [comment]
@ksuprynowicz 
Thanks for the answer, sorry. I don't seem to understand your answer. I'm sorry, can you explain in detail?
As in the picture,
In the left state, no path is created. So I want to move the workbench to the right, but the Z value is negative. I want to get G-CODE that follows STL's XYZ. I expected G-CODE to be made like a white line, but it wasn't. I want the G-CODE to be generated like a white line.
![image](https://user-images.githubusercontent.com/65271457/82185126-b5ba1e00-9923-11ea-966b-a4f05643176a.png)
OR
![image](https://user-images.githubusercontent.com/65271457/82185182-cbc7de80-9923-11ea-83d5-f88efe940c58.png)

**Comment by ksuprynowicz** [comment]
You don't have to move machine area for that. You just have to set "Free movement height" to safe level above your object, and "Operation depth start" to a height above your object. If you also want to set initial and final cutter position a bit higher, set "Use position definition checkbox" and enter coordinates there.
I've just tested it and seems to work fine:
![z](https://user-images.githubusercontent.com/11568651/82210384-4a665100-990f-11ea-8f1a-dcb663d23807.png)

**Comment by mir132** [comment]
@ksuprynowicz 

Thank you for your kindness. 
Is the above explanation only available in version 2.82?
Additionally, I want to install 2.82a blendercam on a window pc. However, an error occurs because the description is a Linux version. I want to know the solution. And I want to know the meaning of abc when using 5 or 6 axis. Sorry to send many questions every time.

![image](https://user-images.githubusercontent.com/65271457/82274097-34619a80-99ba-11ea-9eab-d93fb645378b.png)
![image](https://user-images.githubusercontent.com/65271457/82274158-65da6600-99ba-11ea-938f-468927ceeb20.png)

**Comment by ksuprynowicz** [comment]
It seems like you have to do `pip3 install shapely` again after installing wheel.
As for 5 and 6-axis support, it's unfinished right now. I have a 6-axis machine, but it needs new electronics so I don't have any experience with it.

**Comment by mir132** [comment]
@ksuprynowicz 
Thanks for the answer.
There are additional questions. On the surface
When making a path with an OUTLINEFILL, floating occurs without touching it as shown in the figure.
How can I solve it?

And is there any way to make Gcode draw in the order I want?
For example, how to draw in order from the left when writing letters, and how to fill the inside in parallel after drawing the outline?

![image](https://user-images.githubusercontent.com/65271457/83098473-c3229580-a0e5-11ea-8c33-c0ffa096644c.png)

![image](https://user-images.githubusercontent.com/65271457/83098492-ce75c100-a0e5-11ea-817e-25abb65ace79.png)

**Comment by ksuprynowicz** [comment]
That's a bit surprising. Can you post a simple example file where this occurs?

As for enforcing order, right now you have to create separate operations for that.

**Comment by mir132** [comment]
[test3_0529.zip](https://github.com/vilemduha/blendercam/files/4699250/test3_0529.zip)





I wrapped the svg file on a curved surface.
Then I created a path. The result is the same as the file. Why?
Thanks for your kind answer every time.

**Comment by pppalain** [comment]
issue closed as blender 2.79 is unsuported with new code.
