### ISSUE TITLE
ModulenotFoundError: No module named ocl

### ISSUE THREAD

**Issue by midoec** [vilemduha/blendercam#155]
I just downloaded blendercam and tried to set it up on ubuntu 18.04LTS with blender 2.82a and blender 2.81a they are both giving this error. ModulenotFoundError: No module named ocl

There is a copy of blendercam i downloaded in January. That copy works with blender 2.81a and still works now without Opencamlib. I just wanted to get the latest code and i dont know why its giving the error.

**Comment by ksuprynowicz** [comment]
Thanks for reporting this. I've just added a fix for this, let me know if it works.

**Comment by midoec** [comment]
hello Thanks for fixing it. it works now.

I am really grateful for this addon and i cant thank you guys enough. i have been using it since january and its simply amazing. Thanks once again.

**Comment by ksuprynowicz** [comment]
Nice to hear that :)
Have you checked "show experimental features" in addon preferences? There's more options this way, some are unfinished, but some are very useful.

**Comment by alexpGH** [comment]
HI all,
I still face the above problem with the current master version (fd61ffe 14 days ago).
Did the fix get lost?
