### ISSUE TITLE
`Read-only file system` error on MacOS

### ISSUE THREAD

**Issue by illus0r** [vilemduha/blendercam#160]
Hello there! Thanks for the free and powerful tool!

It looks fascinating, but when I try to calculate path, I get the error:

![image](https://user-images.githubusercontent.com/797993/92579690-8d717900-f29e-11ea-9dc4-a9e496f35d61.png)

Both Blender and its python are in the list of full disk access apps:

![image](https://user-images.githubusercontent.com/797993/92579849-c3aef880-f29e-11ea-8f81-f82db6f9f36f.png)
![image](https://user-images.githubusercontent.com/797993/92579873-cc073380-f29e-11ea-9821-94bb7c561184.png)

How is this solvable?

**Comment by ksuprynowicz** [comment]
Hi!
Have you saved the Blender file to some directory where you have write access before generating gcode?

**Comment by illus0r** [comment]
@ksuprynowicz thank you! It did the trick!

**Comment by ksuprynowicz** [comment]
Nice to hear that :)
