### ISSUE TITLE
[improvement proposal] add G64 gcode path blending option with tolerance in add-on menu

### ISSUE THREAD

**Issue by Olm-e** [vilemduha/blendercam#168]
following the #83 issue and it's proposed solution, add a checkbox and a field in the add-on menu to validate the use and set the tolerance of the G64 code for path blending.
it looks like a needed option for most cuts as arcs are not supported, so to "not burn bits at first cut 'cos you didn't knew about it" ... 
I have from my side validated that just adding the G64 P0.015 parameter on a regular precise enough 18mm / 6mm bit wood cut _helps a lot_ compared to a raw gcode output without path blending (P0.015 could probably be default value)

**Comment by pppalain** [comment]
current pull request addresses this issue.  will be added to CAM movement menu

**Comment by pppalain** [comment]
![image](https://user-images.githubusercontent.com/33393909/102698427-7cc48d80-4213-11eb-83a6-0fbcbd08b39b.png)

**Comment by pppalain** [comment]
today's merge has fixed this issue
![image](https://user-images.githubusercontent.com/33393909/104360133-fb48de00-54e6-11eb-818c-f4eb7e9adeb8.png)
