### ISSUE TITLE
Wrong gcode axis rotation when using 4th axis indexing

### ISSUE THREAD

**Issue by ghost** [vilemduha/blendercam#17]
See discussion on google group:
https://groups.google.com/forum/embed/?place=forum%2Fblender-cam-forum&theme=softgray&hideforumtitle=true&showsearch=false&showpopout=true&showtabs=true&parenturl=http%3A%2F%2Fblendercam.blogspot.ca%2Fp%2Fblog-page.html&afterlogin=&pli=1#!category-topic/blender-cam-forum/development/hQCkP0E5-g8

The A axis should be used for 4th axis indexing?  I have built my own 4th axis along with controller and I have that 4th axis as A based on the literature I have read on the Internet.  It should not matter if the 4th axis is orientated x,y, or z.  The g-code that Blendercam generates uses B axis for rotated indexing when the 4th axis is X.  If I switch the return values in rotTo2axes() in utils.py then A axis gets used properly.

Things get stranger when the 4th axis is selected to Y or Z but I will expand on that later.

**Comment by vilemnovak** [comment]
This is totally unfinished part of Blender CAM - 4 axis code works and was tested, but the machine configuration should be part of the machine settings panel. It was meant to be that way, and I think there are the options for these settings, but not sure how far I got with this back when I was working on this part.

**Comment by nfz** [comment]
Ok, will dig deeper.

**Comment by nfz** [comment]
I found the commented out code that partially deals with this problem.   The Machine Settings properties axis4 and axis5 where commented out in ui.py.  They are not used in utils.py so I will cobble something together as I need indexing working today for a project.  Will be a good way to learn 4th axis stuff.

**Comment by nfz** [comment]
I got it working for the project I needed to finish but I will hold off on a pull request until I get the NC update done.

**Comment by vilemnovak** [comment]
what about this? maybe might go on now?

**Comment by nfz** [comment]
Yep, will commit.
