### ISSUE TITLE
Install Video

### ISSUE THREAD

**Issue by lumenmesh** [vilemduha/blendercam#177]
Has anyone made a tutorial video of install for windows version?   I have no experience with terminals and python but would really like to try blendercam.        Thanks for any help

**Comment by ksuprynowicz** [comment]
Sadly I only have Linux PCs at the moment. If nobody else will do it, can you remind me in about 4 weeks? I plan to install Windows then.

**Comment by pppalain** [comment]
you could install linux in a virtual machine on your computer

**Comment by abosafia** [comment]
dual os is the better option for me.
I think blender runs faster on linux.
I'm using windows10 and linuxmint

**Comment by pppalain** [comment]
install instructions have changed since dependencies autoinstall
