### ISSUE TITLE
Button positioning model

### ISSUE THREAD

**Issue by torvn77** [vilemduha/blendercam#18]
![Menu](https://pp.vk.me/c629513/v629513199/3c12d/hvGxT1mcJSM.jpg)
Hello, I want to offer you in the section "CAM Material size and Position" button instead of the "Position Object" to make two buttons:
1)the First button "Zero of material surface" will configure BlenderCAM for creating NC programs for engraving,
the object will be positioned at the top of the lower region Z<0, and the quick movements will be above zero.
![Engraving](https://pp.vk.me/c629513/v629513199/3c14b/YOSn-fzZzP8.jpg)

2)the Second button "of the Worktable Zero" button to set BlenderCAM to create NC programs for 3D milling reliefs.
The zero pack is placed on the surface of the desktop, and the whole process is conducted in the positive part Z>0
![3D_Model](https://pp.vk.me/c629513/v629513199/3c144/szsBNXYEmQQ.jpg)

I certainly poorly explained, to understand the character of the query show the text and illustrations attached to the milling professional and he will explain what it is.

Original text(Russian):
Здравствуйте, хочу предложить вам в секции "CAM Material size and Position" вместо кнопки "Position Object" сделать две кнопки:
1)Первая кнопка "Zero of material surface" будет настраивать BlenderCAM для создания УП для гравировки,
при этом объект будет позиционироваться в верху нижней области Z<0, а область быстрых перемещений будет выше нуля.
2)Вторая кнопка "Zero of Worktable" кнопка будет настраивать BlenderCAM на создание УП для 3D фрезерования рельефов.
При этом ноль УП распологается на поверхности рабочего стола, а весь процесс ведётся в положительной части Z>0

Я конечно плохо изложил, чтобы понять сущность запроса покажите этот текст и приложенные иллюстрации профессиональному фрезеровщику и он вам объяснит в чём дело.

**Comment by nfz** [comment]
Ok, I could see this being useful.

**Comment by nfz** [comment]
I will put together a little test.

**Comment by nfz** [comment]
Something like this?
![posobjtest](https://cloud.githubusercontent.com/assets/648108/12522911/dde542c8-c129-11e5-8f0d-595a8d40cd0e.png)

**Comment by torvn77** [comment]
>Something like this?
Yes.
