### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by s08glen** [vilemduha/blendercam#186]
Hi,
I am a student and I want to use Blendercam to make some animation for my project.
I want to install this cam on Windows because some of my side project is depend on Windows OS.

I knew that there are some Python package need to be installed before using it, so I followed the following unoffical youtube video and failed.
https://www.youtube.com/watch?v=IDS8GNq1LTE
https://www.youtube.com/watch?v=k4y3rRAvfl0

When I tried to enable the "Scene:CAM" in Blender Preferences, it show me the error message such like "ImportError: DLL load failed: Cannot find module" " Traceback -> import numpy -> from . import core -> raisw ImportError(msg)" " Import the numpy C-extensions failed", I also cannot turn CAM Render Engine in Blender Scene.
I have checked numpy and shapely had been installed correctly.

Is there any other way to install this project in Windows environment instead of Linux OS? 
Thanks a lots!

**Comment by pppalain** [comment]
join https://riot.im/app/#/room/#blendercam:matrix.org chat and usually someone can help you there in various time zones.

**Comment by hroma** [comment]
I've also failed to install blendercam under windows.
Suggestion: 
Blender as a portable version for windows https://www.blender.org/download/Blender2.93/blender-2.93.4-windows-x64.zip/ . Wouldn't be possible that someone (else than nooby like me) manage to include all dependencies required to a portable version? Windows users would be so gratefull :-)

**Comment by abosafia** [comment]
join https://riot.im/app/#/room/#blendercam:matrix.org chat and usually someone can help you there in various time zones.

**Comment by wohali** [comment]
In the attached zip is the `ocl.pyd` file you need for the current Blender 3.2, Windows 64-bit, embedded Python 3.10.2. 

Put this in the `Blender 3.2\3.2\python\lib\site-packages` directory of your installation.

Hope this helps someone - took me a day to sort out compiling it....

[ocl.zip](https://github.com/vilemduha/blendercam/files/8923087/ocl.zip)

**Comment by pppalain** [comment]
I recently installed on version Blender 3.1 on windows without OCL and posted a video. https://youtu.be/RXpGLJz7ZIs OCL is optional and new versions of blender have better collision making OCL really optional.

**Comment by wohali** [comment]
> I recently installed on version Blender 3.1 on windows without OCL and posted a video. 

Fortunately this part is easy, or at least I think so :) thank you for sharing this for others!

I wanted to mess with waterline and OCL.

**Comment by abosafia** [comment]
> 

Water line now works with ocl
You can try
https://github.com/pppalain/blendercam

**Comment by abosafia** [comment]
> In the attached zip is the `ocl.pyd` file you need for the current Blender 3.2, Windows 64-bit, embedded Python 3.10.2.
> 
> Put this in the `Blender 3.2\3.2\python\lib\site-packages` directory of your installation.
> 
> Hope this helps someone - took me a day to sort out compiling it....
> 
> [ocl.zip](https://github.com/vilemduha/blendercam/files/8923087/ocl.zip)

Thanks for the file. It's working very good. But dependencies have to be installed.

**Comment by joemarshall** [comment]
https://pypi.org/project/opencamlib/

In case anyone is looking for it, it's on pypi as an installable package now.

**Comment by joemarshall** [comment]
https://pypi.org/project/opencamlib/

In case anyone is looking for opencamlib  it's on pypi as an installable package now. 

Blendercam on pypi seems like an obvious next step now

**Comment by joemarshall** [comment]
Install from https://github.com/pppalain/blendercam

and it works fine on windows

**Comment by pppalain** [comment]
new version of blendercam now autoinstalls dependencies
