### ISSUE TITLE
Selecting Ball presets doesn't update the tool settings and throws an error.

### ISSUE THREAD

**Issue by ecv80** [vilemduha/blendercam#189]
Blender 2.93.1

Selecting Ball presets doesn't update the tool settings and throws the following:

Error: Failed to execute the preset: TypeError('bpy_struct: item.attr = val: enum "BALL" not found in (\'END\', \'BALLNOSE\', \'BULLNOSE\', \'VCARVE\', \'BALLCONE\', \'LASER\', \'PLASMA\', \'CUSTOM\')')

It looks like it's simply a matter of renaming some entries.

**Comment by ksuprynowicz** [comment]
Hi!
I just accepted two pull requests with various fixes. Can you try again and let me know if it works now?

**Comment by ecv80** [comment]
Oh, unfortunately it doesn't appear to work, but maybe I didn't update properly. This is all I did: "git pull" and I restarted Blender. Is that enough? Thanks.

**Comment by ecv80** [comment]
Also is there a place to have a brief chat? I'm pretty much new to CNC milling and I have a question regarding roughing and finish operations in BlenderCAM.

**Comment by pppalain** [comment]
that was because ball was deleted and not supported by opencamlib.  use ballnose instead
