### ISSUE TITLE
Blender 2.93 crashes when enabling OpenCamLib

### ISSUE THREAD

**Issue by dexington** [vilemduha/blendercam#191]
[KuduQ Engrave test 2.blend.zip](https://github.com/vilemduha/blendercam/files/6834766/KuduQ.Engrave.test.2.blend.zip)
I've installed BlenderCam and OpenCamLib according to the latest instructions under Ubuntu 20.

I'm able to generate a parallel toolpath and simulate it with 'exact mode' enabled.  (See attached .blend file)
However, when enabling OpenCamLib, blender crashes. Strangely, it doesn't generate a blender.crash.txt file. 
BTW it seems "Exact Mode" cannot be deactivated once enabled.

I noticed one error when installing OpenCamLib using "cmake -DBUILD_PY_LIB=ON -DBUILD_CXX_LIB=ON -DUSE_PY_3=ON .."
as follows:
"Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)"
Other than that I didn't see any errors.

INTENDED ROUTER: Shapeoko 4 XL

**Comment by abosafia** [comment]
hi dexington
there is somthing wrong with your model I don't know 
I exported it as stl 
then imported it  in new file works fine
join us in
https://riot.im/app/#/room/#blendercam:matrix.org
we can help better
[KuduQ Engrave test .blend.tar.gz](https://github.com/vilemduha/blendercam/files/6834886/KuduQ.Engrave.test.blend.tar.gz)

**Comment by dexington** [comment]
@abosafia Thank you. I will join you there.

**Comment by TurBoss** [comment]
hello

"Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)"

```
sudo apt install doxygen
or doxygen-dev
```
but this is optional to generate docs

**Comment by dexington** [comment]
@TurBoss Thank you.
