### ISSUE TITLE
'Opencamlib NOT installed'

### ISSUE THREAD

**Issue by d8sconz** [vilemduha/blendercam#198]
I can't install Opencamlib for some reason. It is installed, simlinks in place, alternative script path in preferences. I've checked, double checked and repeated the whole setup process but I continue to get this message under 'CAM info & warnings' tab. I'm using Blender 2.93.1 on Linux Mint 20.2.

**Comment by neuroblossom** [comment]
Im having the same issue, 'Opencamlib NOT installed'  Blender 3.1.0 MacOS Monterey 12.3. Have also tried copying the .py and .so library files into my blender python site-packages folder as well as symlinking.

**Comment by abosafia** [comment]
I'm using Linux mint and it is installed.
Join us at 
https://matrix.to/#/#blendercam:matrix.org

**Comment by pppalain** [comment]
new version auto installs dependencies including shapely
