### ISSUE TITLE
Beginner's question: "use exact mode" 

### ISSUE THREAD

**Issue by Karsten68** [vilemduha/blendercam#201]
Hi.
I am struggling a bit after installing blendercam with opencamlib on blender 2.9.2., Debian 10 Machine.
It's probably just a "user error": 
I see from the documentation, that the "use exact mode" setting is described and shown in the "CAM optimisation" panel. However, it seems to be missing on my display? What am I doing wrong?

![Bildschirmfoto vom 2022-02-02 23-12-25 2](https://user-images.githubusercontent.com/98871282/152246898-ef0defa6-f3be-4fff-b8f5-2e7018e23e62.png)

**Comment by abosafia** [comment]
Hi.
Nothing missed. It doesn't work without exact mode. That's why it isn't there to choose.

**Comment by Karsten68** [comment]
Thanks for the quick answer.
