### ISSUE TITLE
Scale problem (and a hacked fix)

### ISSUE THREAD

**Issue by imerso** [vilemduha/blendercam#202]
So, as probably many are suffering with this bug, where you set the scene scale to metric, millimeters and 0.001 scale -- which makes sense because you want to work in millimeters -- but then get exported gcode with huge numbers...

What worked for me (not sure but maybe you will need different number here) was:

gcodepath.py line 141:
```
        unitcorr = 1;
```

gcodepath.py line 238:
```
        fmh = round(free_movement_height, 2)
```

Well, as said, your number might be different, but these two changes solved the problem for me and now I'm getting proper gcode scale.

I may come back to this in the future, and make a definitive fix. But for now it is enough for me. =)

Good luck.

**Comment by imerso** [comment]
Well, it's quite buggy... but I like it and will see if I manage to reserve free time to spend fixing some of them.

**Comment by abosafia** [comment]
We never had this issue.
please join us at
https://riot.im/app/#/room/#blendercam:matrix.org

**Comment by fl0wm0ti0n** [comment]
i run into this... i have no clue... everything is correct in mm sizes... but the gcode output is x10 bigger...

![image](https://user-images.githubusercontent.com/24993288/185794033-e1ef9341-bfad-4a49-9fcd-24b3ec179c0e.png)
![image](https://user-images.githubusercontent.com/24993288/185794059-c14dc9fa-1a6a-4cb1-bae4-c969f08c59c8.png)

[Op_Cube_1.gcode.txt](https://github.com/vilemduha/blendercam/files/9389219/Op_Cube_1.gcode.txt)

**Comment by fl0wm0ti0n** [comment]
> i run into this... i have no clue... everything is correct in mm sizes... but the gcode output is x10 bigger...
> 
> ![image](https://user-images.githubusercontent.com/24993288/185794033-e1ef9341-bfad-4a49-9fcd-24b3ec179c0e.png) ![image](https://user-images.githubusercontent.com/24993288/185794059-c14dc9fa-1a6a-4cb1-bae4-c969f08c59c8.png)
> 
> [Op_Cube_1.gcode.txt](https://github.com/vilemduha/blendercam/files/9389219/Op_Cube_1.gcode.txt)

Ok the solution for me was, to start a new project and from begining, set the settings to Millimeters and dont set the scaling to 0.01mm, let it on 1mm. in viewport set it to 0.01
