### ISSUE TITLE
Spindle RPM below 1000 not possible 

### ISSUE THREAD

**Issue by sbolten** [vilemduha/blendercam#203]
Hi,

why can the spindle rpm in the cam feed rates panel not be set to values below 1000? Might not be used that often but I don't see the reason to prevent this.

S.

**Comment by abosafia** [comment]
Do you need it less than 1000?
What is the minimum value could be used?
I'll change it

**Comment by sbolten** [comment]
I would start with 100 or maybe even 0. This way way you could generate grbl which just simulates the moves without actually milling.

**Comment by TurBoss** [comment]
I think 0 should be fine too
