### ISSUE TITLE
BAS relief as standalone script

### ISSUE THREAD

**Issue by sandorkonya** [vilemduha/blendercam#208]

**Comment by sandorkonya** [comment]
@vilemduha thank you for your reply.
... I was not sure that it makes sense what i ask.

I will try to fiddle around with the code.

**Comment by abosafia** [comment]
> Yeah, even if you deleted the question for some reason, the whole addon can be easily separated from Blender - it's in blender just for convenience...

Welcome back blendercam master
Thanks for the great add-on

**Comment by abosafia** [comment]
> @vilemduha thank you for your reply. ... I was not sure that it makes sense what i ask.
> 
> I will try to fiddle around with the code.

Join us at https://matrix.to/#/#blendercam:matrix.org
