### ISSUE TITLE
Export Gcode in mm

### ISSUE THREAD

**Issue by wcanarro** [vilemduha/blendercam#228]
Hi, my blender project is 30mm x 30mm but when I export the gcode all coordinates are set to an area of 300mm x 300mm.
I use blendercam 0.9.3
thank you

**Comment by abosafia** [comment]
Hi,
I think it's a scale issue.
Try  scale 1

**Comment by abosafia** [comment]
https://github.com/vilemduha/blendercam/issues/202

**Comment by wcanarro** [comment]
Hi, yes, solved using the fix #202
