### ISSUE TITLE
Generating Gcode for laser with parallel strategy

### ISSUE THREAD

**Issue by wcanarro** [vilemduha/blendercam#229]
Hi, I am getting the error showed in the picture
![Screenshot_20230210_112454](https://user-images.githubusercontent.com/48019141/218068771-87c7b265-51f9-4f4a-b978-2a4f251e52d1.png)
maybe I am missing something...I dont think there is an issue...any help?

**Comment by TurBoss** [comment]
hello, looks like the dial.002 was created outside the Scene Collection

can you move it to that collection and try again?

thanks

**Comment by wcanarro** [comment]
yes, the error is gone and the gcode generated, but I dont see the result inside blender...and the mesh must be in the main directory (the scene collection and not in sub folder)

**Comment by wcanarro** [comment]
Now, if I try on the same mesh, parallel strategy and select the laser (preset -> laser) i get this error
![Screenshot_20230210_125230](https://user-images.githubusercontent.com/48019141/218086485-813e3f89-4bf6-426b-998d-72a684201108.png)

**Comment by abosafia** [comment]
Laser cannot be used with 3d strategies like parallel.
It is for pocket and profile cut.

**Comment by pppalain** [comment]
I consider the issue to be closed.  Training wheels will be added for people not to choose the parallel or drop cutter strategies to laser tool.
