### ISSUE TITLE
Generated grbl g-code does not have necessary G1 commands

### ISSUE THREAD

**Issue by twchambers** [vilemduha/blendercam#230]
I'm using blendercam with a Workbee Z1+ which runs a Duet 2 control board.
It seems that this board requires a G1 command on every line; simply using a single G1 and then providing new X and Y coordinates on each line is not sufficient.
How can I tell blendercam to include these commands? Is it necessary to edit the grbl postprocessor? My current solution is to manually edit the gcode before running, but obviously this is less than ideal!

**Comment by pppalain** [comment]
Try the ISO post processor.  Rename the file .tap to .gcode.

**Comment by twchambers** [comment]
Perfect, that's solved it, thanks.
