### ISSUE TITLE
Crash using Blender 3.5.1

### ISSUE THREAD

**Issue by tirithen** [vilemduha/blendercam#237]
Hi! While trying out this interesting tool I have a crash when clicking the "Drawer" button:

```
AttributeError: Calling operator "bpy.ops.curve.simple" error, could not be found
```

It seems like the .simple API has been removed? I found this Q/A https://blender.stackexchange.com/a/276486 and there they switched to `bpy.ops.curve.primitive_bezier_curve_add`, not being so familiar with the Blender API, is that a viable alternative for newer Blender versions?

![Skärmbild från 2023-05-23 06-49-22](https://github.com/vilemduha/blendercam/assets/245811/b6f42eb8-2160-416d-8bb1-24a0e7e6be60)

**Comment by pppalain** [comment]
you need to activate the plugin curve extra it is included in blender but not activated

**Comment by tirithen** [comment]
Thanks a bunch! I'll try that out next time I use the plugin!
