### ISSUE TITLE
problem with Blendercam

### ISSUE THREAD

**Issue by ionapostol** [vilemduha/blendercam#238]
I have 3.5.0 and I get this error when  I try to calculate gcode.
Any sugestion ?
![blendercam](https://github.com/vilemduha/blendercam/assets/67235879/f65c802b-e646-4905-92d8-4b24d68a71be)

**Comment by TurBoss** [comment]
hello,

I think that you need to save the blend first to some place you have write permissions
then you will be able to export the gcode and will apear in the same place the the blend file is saved

**Comment by ionapostol** [comment]
Thank you. Seems you are right.
