### ISSUE TITLE
operations order

### ISSUE THREAD

**Issue by GvBon** [vilemduha/blendercam#250]
Is there a way to order the operations on the X-axis? So the separate operations ar ordered from left to right? I would need this for a specific machine.

**Comment by pppalain** [comment]
I am not certain what you mean but short answer would be no

**Comment by GvBon** [comment]
I mean that from a complete cnc job all different operations can be sorted depending on their starting point. In my case it is necessary that the most left operation is done first, then the one next to it to the right, etc etc.
