### ISSUE TITLE
Blender settings unclear / blendercam unusable with simple demo cube

### ISSUE THREAD

**Issue by xmarduel** [vilemduha/blendercam#256]
Being unable to use blendercam correctly in a trivial use case (example: adding in an empty scene a cube of dimension 50mmx50mmx10mm and trying to perform a Profile  outside operation with layer 1mm), I have noticed that I always get some inconsistency concerning the scene units and scale with blender cam. 
Not only I get wrong toolpaths, but they are also saved as gcode X 20000 Y 20000 or the like (i.e. in order of magnitude of meters)

Indeed, when setting in blender the Scene "**Units**" with "**Length**": "**Millimeters**", blender real specialists seem always to set together with Millimeters the "**Unit Scale**" to **0.001**. I have seen this in YouTube tutorials with the CAD-Sketcher add on. Then working with these settings is completely Ok.  Further, in the **Viewport Overlays** settings, in order to get a nice floor with the grid, the "**Guide**" **Scale** is also set to **0.001**.

Does this match the settings with which blendercam should be used?

It seems that blendercam does not rely on these settings, but keeps the "Unit Scale" to 1, and this ruins everything in this simple case.

So (not so) long story short, could you simply provide a step by step tutorial with this simple use case of adding a cube of dimension 50mmx50mmx10mm , layer 1mm, Profile op, and showing us how to successfully generate a correct gcode file?

Right blender/blendercam settings are of course key for success, and should be well documented!

I've got the latest blendercam 3.11 installed on windows

Best regards

PS: I do not provide a step by step how to repeat, because everyone I guess trying this simple use case will experience the same problems that I've encountered.

**Comment by abosafia** [comment]
Use millimeter and scale 1
