### ISSUE TITLE
bpy.ops.curve.simple not found

### ISSUE THREAD

**Issue by ReeceRobinson** [vilemduha/blendercam#257]
I have been trying to get all the generative features working for this add-on (version 0.9.10) but I keep getting the python exception that bpy.ops.curve.simple is not found. I am using Blender 3.5.1 on an Intel Mac. I can't seem to find any reference to this method searching google. What am I missing?

**Comment by pppalain** [comment]
oh, you have to tick the curve extra plugin in blender.  sorry for the delay, we are more responsive on the chat.

**Comment by pppalain** [comment]
![image](https://github.com/vilemduha/blendercam/assets/33393909/082d8fc6-8fda-4aa5-9a79-6ece14f21bbc)

**Comment by ReeceRobinson** [comment]
Thanks for responding. That worked.
