### ISSUE TITLE
A groove is made narrower

### ISSUE THREAD

**Issue by denprog** [vilemduha/blendercam#264]
I want to make groove with the Parallel path. But it always is narrower after CNC than it is in Blender. I tried different options.
![изображение](https://github.com/vilemduha/blendercam/assets/617910/eca0f534-7631-4c6f-83c7-d9ff14cba92d)
For example, this picture shows a groove and such path settings:
Strategy: Parallel
Distance between toolpaths: 2 mm
Distance along toolpaths: 0.2 mm
Use layers: 5 mm
Operation depth start: -1 mm
Movement type: Meander / Zig Zag
Cutter: End
Cutter diameter: 3 mm.
The picture shows that paths are too far from the walls of the groove.
What's wrong in my path? How to make a groove exactly as in Blender?

**Comment by denprog** [comment]
I don't use skin. Are talking about this group? https://groups.google.com/g/blender-cam-forum

**Comment by abosafia** [comment]
https://matrix.to/#/#blendercam:matrix.org
