### ISSUE TITLE
Allow non-cut movements to be hidden

### ISSUE THREAD

**Issue by davisburnside** [vilemduha/blendercam#265]
Some CAM makers, like Fusion360, color-code different movement types (Blue = Cut operations, Yellow = linking moves, Green = Ramping, Red = Plunging). They also give the ability to show/hide certain types, for better UI Clarity. 

It would be nice if BlenderCAM offered this feature too. Maybe individual cam_path meshes could have edges tagged with movement type, then in edit mode a button could be used to hide certain types? I would like to collaborate in making this.

![Screenshot 2024-07-04 124550](https://github.com/vilemduha/blendercam/assets/36344011/c01dddd6-fc02-4095-b3a1-357bc95d7f4c)
,

**Comment by pppalain** [comment]
join us on chat.(https://riot.im/app/#/room/#blendercam:matrix.org)
