### ISSUE TITLE
Equation package:  AttributeError: `np.Inf` was removed in the NumPy 2.0 release

### ISSUE THREAD

**Issue by aak67** [vilemduha/blendercam#266]
NumPy 2.0 use np.inf and no longer np.Inf and np.nan instead of np.NaN
This is an issue of the Equation package of course and not blendercam.

Workaround: just edit the file and use lowercase characters (e.g. in manjaro linux /usr/lib/python3.12/site-packages/Equation/equation_base.py)

**Comment by pppalain** [comment]
thanks for reporting this.  the fix was to rewrite the code to not use Equation at all.   The reason is that we had on control of legacy packages and their continued compatibility.
