### ISSUE TITLE
Help wanted: "No module named `curve_simplify` "

### ISSUE THREAD

**Issue by ParsaJafarian** [vilemduha/blendercam#268]
## Problem Summary
After manually installing some python packages (see issue #267), I got another module error:
![image](https://github.com/user-attachments/assets/e022d5d7-0912-4d7a-9cce-5701cf0d8b15)

This time, however, when I try to install it through pip by running `.\python.exe -m pip install curve_simplify`
 I get the following error:
```
ERROR: Could not find a version that satisfies the requirement curve_simplify (from versions: none)
ERROR: No matching distribution found for curve_simplify
```

I am not sure what to do now. Any help would be appreciated.

**Comment by abosafia** [comment]
Try this 
https://github.com/pppalain/blendercam

**Comment by pppalain** [comment]
blender 4.2 has made quite a few problems.  Blender makes updates and those break things for us
