### ISSUE TITLE
error with a remove_doubles operator

### ISSUE THREAD

**Issue by luigipacheco** [vilemduha/blendercam#271]
Hello I have BlenderCAM running on windows with blender 4.2 so maybe it not compatible.

I get the following errors when using the curve tools:
AttributeError: Calling operator "bpy.ops.curve.remove_double" error, could not be found

I have installed all the required dependencies

**Comment by ydnatag** [comment]
I had this error last week and I reported it to the maintainer: https://github.com/pppalain/blendercam/issues/166

TL;DR: Blender now does not include some extensions by default. Install `Simplify curves+` and `Extra Cruve`

**Comment by abosafia** [comment]
Some updates to curve remove doubles on the unstable branch.
https://github.com/pppalain/blendercam

**Comment by Kovadon** [comment]
Installed both `Simplify Curves+` and `Extra Curve` in `4.2` and `4.1` and am still experiencing this error

**Comment by pppalain** [comment]
should be fixed with latest release

**Comment by willpuckett** [comment]
I'm getting fhis error occasionally as well when trying to process a cam operation. I have both Simplify curves+ and Extra Curve installed...

![Image](https://github.com/user-attachments/assets/ebd46a4a-037c-41b5-9662-a5a027cedab4)

**Comment by willpuckett** [comment]
I'm getting 'context is incorrect' in object mode. 

It can usually be avoided by selecting an object and running the op again.

![Image](https://github.com/user-attachments/assets/8cb28d01-3987-4ebb-a09a-2126d01ee881)

**Comment by dynamodan** [comment]
This is still a bug in Blender 4.5 with Simplify Curves+ and Extra Curves plugins installed.  Will try 4.1.

**Comment by dynamodan** [comment]
Actually it's this bug:
```
Exception Thrown in Tick: 'bpy_prop_collection[key]: key "Scripting" not found'
Error: Error: Python: Traceback (most recent call last):
  File "/home/dynamo/.config/blender/4.5/extensions/user_default/fabex/operators/curve_tools_ops.py", line 636, in execute
    bpy.ops.curvetools.operatorsplinesremoveshort()
  File "/usr/share/blender-4.5.5-linux-x64/4.5/scripts/modules/bpy/ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Calling operator "bpy.ops.curvetools.operatorsplinesremoveshort" error, could not be found
Location: /usr/share/blender-4.5.5-linux-x64/4.5/scripts/modules/bpy/ops.py:109
```
