### ISSUE TITLE
Translations at Italian languages?

### ISSUE THREAD

**Issue by kylotron** [vilemduha/blendercam#34]
Hi all,
is possible to translate blendercam at other languages?

**Comment by nfz** [comment]
Yes, its possible.  The plugin is not setup right now for other languages but it would not take much to do.

**Comment by kylotron** [comment]
Ok... ;)

**Comment by nfz** [comment]
Are you interested in providing the Italian translations?

**Comment by kylotron** [comment]
Yes... :P

**Comment by nfz** [comment]
Ok, I will start setting up support for International Languages support.  Will take a few days.

**Comment by kylotron** [comment]
Beautiful. 
Thank you!

**Comment by nfz** [comment]
Ok, was trying to use the Blender built in translation addon to setup a .po file for translations but encountered some issues.  This will take more time to get going.  I am investigating if its the Blender addon and/or blendercam that is causing the problem.

**Comment by nfz** [comment]
Still working on this but hit a bit of a brick wall.  The blender addon works but it modifies the main blender translation file.  Only patches for official blender addon translations will get excepted into the main Blender git repo.  Looking at a different way of doing the translation similar to the way [bCNC](url) does it.

**Comment by pppalain** [comment]
this enhancement was never finished
