### ISSUE TITLE
Problem on parallel strategy

### ISSUE THREAD

**Issue by kylotron** [vilemduha/blendercam#64]
Friday works.
Today not work!

![partiinpolicarbonato_3a blend](https://cloud.githubusercontent.com/assets/5792338/15646048/e537b758-265b-11e6-9479-253e14ffddfa.png)

```
Traceback (most recent call last):
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/ops.py", line 218, in execute
    utils.getPath(context,o)
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/utils.py", line 3324, in getPath
    getPath3axis(context,operation)
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/utils.py", line 2890, in getPath3axis
    chunks.extend(sampleChunks(o,pathSamples,layers))
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/utils.py", line 332, in sampleChunks
    oclSample(o, pathSamples)
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/opencamlib/opencamlib.py", line 106, in oclSample
    exportModelsToSTL(operation)
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/opencamlib/opencamlib.py", line 88, in exportModelsToSTL
    bpy.ops.export_mesh.stl(check_existing=True, filepath=file_name, filter_glob="*.stl", use_selection=True, ascii=False, use_mesh_modifiers=True, axis_forward='Y', axis_up='Z', global_scale=1.0)
  File "/home/kylotron/Scaricati/blender-2.76b-linux-glibc211-x86_64/2.76/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "use_selection" unrecognized

location: <unknown location>:-1

bpy.context.space_data.recent_folders_active = 2

```

**Comment by kylotron** [comment]
No... ok. It's work.:(

**Comment by kylotron** [comment]
Please verify "exact mode" with Parallel .

**Comment by kylotron** [comment]
![parallel-exact_1 blend](https://cloud.githubusercontent.com/assets/5792338/15646849/5a61f116-2660-11e6-9e78-b782eed8dfba.png)

**Comment by nfz** [comment]
Are you still having a problem with Use exact mode + OpenCAMlib?

**Comment by kylotron** [comment]
Yes... :(

This is the first test....

![partiinpolicarbonato_1](https://cloud.githubusercontent.com/assets/5792338/15774800/a923c1fa-297e-11e6-8bb4-9a4943795c3e.png)
![partiinpolicarbonato_2](https://cloud.githubusercontent.com/assets/5792338/15774801/a9249fc6-297e-11e6-903d-4b45cad6591a.png)
![partiinpolicarbonato_3](https://cloud.githubusercontent.com/assets/5792338/15774803/a9276ad0-297e-11e6-91a7-ab196efe74d5.png)
![partiinpolicarbonato_4](https://cloud.githubusercontent.com/assets/5792338/15774802/a927469a-297e-11e6-94be-3ac5c3cd1c44.png)

I made a new working process with parallel strategy, "exact mode" and OpenCAMlib library activated. This is the error generated:

`progress{processing curve 25.0%}
progress{processing curve 50.0%}
Traceback (most recent call last):
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/ops.py", line 218, in execute
    utils.getPath(context,o)
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/utils.py", line 3329, in getPath
    getPath3axis(context,operation)
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/utils.py", line 2895, in getPath3axis
    chunks.extend(sampleChunks(o,pathSamples,layers))
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/utils.py", line 332, in sampleChunks
    oclSample(o, pathSamples)
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/opencamlib/opencamlib.py", line 106, in oclSample
    exportModelsToSTL(operation)
  File "/home/kylotron/Scaricati/blendercam/scripts/addons/cam/opencamlib/opencamlib.py", line 88, in exportModelsToSTL
    bpy.ops.export_mesh.stl(check_existing=True, filepath=file_name, filter_glob="*.stl", use_selection=True, ascii=False, use_mesh_modifiers=True, axis_forward='Y', axis_up='Z', global_scale=1.0)
  File "/home/kylotron/Scaricati/blender-2.76b-linux-glibc211-x86_64/2.76/scripts/modules/bpy/ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "use_selection" unrecognized

location: <unknown location>:-1

location: <unknown location>:-1
`




This is the second test

![schermata del 2016-06-03 11 37 19](https://cloud.githubusercontent.com/assets/5792338/15774976/925c6b2e-297f-11e6-9860-908a6d0e1418.png)

**Comment by kylotron** [comment]
Another test...

1) Parallel + angle = 90° + Exact Mode + OpenCAMLib + Ramp In ----------- (no Use Layers)
![schermata del 2016-06-03 11 47 29](https://cloud.githubusercontent.com/assets/5792338/15775222/09a384fa-2981-11e6-935d-da3b18efbf1b.png)

2) Parallel + angle = 90° + Exact Mode + OpenCAMLib  ----------- (no Ramp In) (no Use Layers)
![schermata del 2016-06-03 11 49 16](https://cloud.githubusercontent.com/assets/5792338/15775273/4a9f1af0-2981-11e6-90de-cc69e26d37e1.png)

3) Parallel + angle = 90° + Exact Mode ----------- (no OpenCAMLib) (no Ramp In) (no Use Layers)
![schermata del 2016-06-03 11 50 36](https://cloud.githubusercontent.com/assets/5792338/15775291/685a4952-2981-11e6-82c2-318083cff854.png)

4) Parallel + angle = 90° ----------- (no Exact Mode) (no OpenCAMLib) (no Ramp In) (no Use Layers)
![schermata del 2016-06-03 11 51 23](https://cloud.githubusercontent.com/assets/5792338/15775323/83656a38-2981-11e6-85b0-613aded6ef22.png)

5) Parallel + angle = 90° + OpenCAMLib ----------- (no Exact Mode) (no Ramp In) (no Use Layers)
![schermata del 2016-06-03 11 52 25](https://cloud.githubusercontent.com/assets/5792338/15775341/a805894a-2981-11e6-951d-dc424092e4ab.png)

6) Parallel + angle = 90° + OpenCAMLib + Ramp In ----------- (no Exact Mode) (no Use Layers)
![schermata del 2016-06-03 11 53 10](https://cloud.githubusercontent.com/assets/5792338/15775353/c4b26d24-2981-11e6-86b3-fda1d4bf6cd8.png)

**Comment by nfz** [comment]
I am not able to re-create this. Could you post the blend file here?  You can drag and drop the zip into the message area.

**Comment by kylotron** [comment]
This is by test file
[test.blend.zip](https://github.com/vilemnovak/blendercam/files/300028/test.blend.zip)

**Comment by nfz** [comment]
Thanks for the file.
I now get the same as what you get.

**Comment by ksuprynowicz** [comment]
Hi!
I've just checked the file you attached and it works perfectly with:
Exact Mode + OpenCAMLib ----------- (no Ramp In) and Blender 2.77a
(OpenCAMLib is only used when both 'Exact Mode' and 'use OpenCAMLib' are active)
The error you are getting is due to recent Blender API change. Try using version 2.77a or newer.
When Ramp In is activated, there's always empty trajectory, no matter if OpenCAMLib is active or not.
