### ISSUE TITLE
Issue with OpenCAMLib guide.

### ISSUE THREAD

**Issue by taras-ko** [vilemduha/blendercam#73]
Hi. Tried to use [this](https://github.com/vilemnovak/blendercam/wiki/Using-BlenderCAM-with-OpenCAMLib) mini-guide and get failed.
![opencamlib_error](https://cloud.githubusercontent.com/assets/1148481/16542420/50fc0b7e-40b0-11e6-9f1e-8722358e6353.png)
Any ideas? Thanks.

**Comment by ksuprynowicz** [comment]
Hi!
There was a change in parameters accepted by Blender's STL export function recently and I've updated OpenCAMLib interface to be compatible with it. Can you try with more recent Blender version, like 2.77a?

**Comment by taras-ko** [comment]
Yeap. It works with 2.77a. Unfortunatelly there are no support for modifiers, disscussed ealier in #63 
Also I need to know what strategies OpenCamLib is supporting in blendercam property panel.
Thanks.

**Comment by taras-ko** [comment]
Also I found "Outline fill" strategy is very useful for my projects. But Its calculaition time terribly long. I'm curious wether OpenCamLib supports calculation of such strategy. Thanks.

**Comment by ksuprynowicz** [comment]
It partially does. You have to select both "use exact mode" and "use OpenCAMLib". The outline is still computed and offsetted by BlenderCAM, but path sampling(the most time consuming part) is then done by OpenCAMLib. I've just tested it on old 24-core machine, and it's way faster than original sampling algorithm. It also works with 'Carve' and some other operations. Let me know if it works for you.

**Comment by ksuprynowicz** [comment]
And as for modifiers, I'll have a look today, I think that there's a simple fix for it.

**Comment by pppalain** [comment]
opencamlib now autoinstalls along with other dependencies
