### ISSUE TITLE
[UI improvement proposals] Distance between toolpathes, visibility of toolpathes, bridges source

### ISSUE THREAD

**Issue by taras-ko** [vilemduha/blendercam#75]
1. Distance between toolpathes should be measure in percents of current cutting tool diameter. Default distance should be 40% of cutting tool diameter.
2. By selecting of each generated toolpath other toolpathes should be hidden.
3. Add possibility to use signle objects for bridge generation.

**Comment by ksuprynowicz** [comment]
1. I think that both distance in millimeters and tool diameter percentage is reasonable, but I personally prefer having distance in millimeters - it's done this way in a lot of commercial software and it's easier to estimate surface roughness after parallel pass. On the other hand if methods like trochoidal machining were implemented, percentage would be a good idea for them(it's directly related to cutter load).
2. I strongly disagree with this - while automatically selecting toolpath when the operation is selected is a good idea, hiding other toolpaths automatically could lead to very expensive mistakes. Frequently a single feature is done with multiple operations, for example a roughing pass and two finishing passes for a pocket(walls and bottom). Seeing them all at once is required to prevent undercutting and breaking cutter on finishing pass(Or even damaging spindle when using very large indexable cutters). While a lot of toolpaths visible at once can be unreadable, they can be easily and selectively hidden from outliner.

**Comment by taras-ko** [comment]
> Frequently a single feature is done with multiple operations, for example a roughing pass and two finishing passes for a pocket(walls and bottom). Seeing them all at once is required to prevent undercutting and breaking cutter on finishing pass(Or even damaging spindle when using very large indexable cutters).

This feature is can be nicely seen in your CNC controller graph window, I guess. For example: I use LinuxCNC and it draws a trace line for previous toolpathes. It helps me do not lost in number of toolpathes.

**Comment by ksuprynowicz** [comment]
For some controllers and small programs it can be done this way, but for larger ones (several gigabytes, 20 or more hours on fast CNC machine) there's no controller that can show this in practical way. And in such cases costs in lost material can easily run into thousands of dollars.

**Comment by taras-ko** [comment]
> I strongly disagree with this - while automatically selecting toolpath when the operation is selected is a good idea, hiding other toolpaths automatically could lead to very expensive mistakes.
Back to the discussion again. I think, at least, making the toolpath automatically visible (if it's hidden) on tool operation selection improve usability of Blendercam. How do you think?

**Comment by ksuprynowicz** [comment]
> Back to the discussion again. I think, at least, making the toolpath automatically visible (if it's hidden) on tool operation selection will improve usability of Blendercam. How do you think?

Definitely yes :) Automatic selection would be also practical.

**Comment by ksuprynowicz** [comment]
As I think of it, automatic hiding of toolpaths would also be very useful (sometimes scene gets cluttered horribly), but it should be available as an option/checkbox.

**Comment by ksuprynowicz** [comment]
I didn't look much at BlenderCAM GUI code(only to add OpenCAMLib checkbox), but I think that there's an event that happens when operation is selected - code for your suggestion could be added there.

**Comment by taras-ko** [comment]
Ok. I'll try to dig in the code.

**Comment by taras-ko** [comment]
> As I thought more about it, automatic hiding of toolpaths would also be very useful (sometimes scene gets cluttered horribly), but it should be available as an option/checkbox.

I've just added a pull request with this feature that we disscussed, could you please verify? It's #81

**Comment by jeffmd** [comment]
I have % tool diameter for distance between toolpaths in my own branch along with actual distance.  You can change one and the other will update automatically.  Not sure if that is what you are looking for.
![percenttooldiamter](https://cloud.githubusercontent.com/assets/20491679/16938515/25915f9c-4d4f-11e6-95b9-10e4ebb92163.png)

**Comment by taras-ko** [comment]
> I have % tool diameter for distance between toolpaths in my own branch along with actual distance. You can change one and the other will update automatically. Not sure if that is what you are looking for.
Exactly! It would be great to have it in master branch.

**Comment by jeffmd** [comment]
I don't have write access to this repo anymore so will do a pull request.

**Comment by ksuprynowicz** [comment]
> I have % tool diameter for distance between toolpaths in my own branch along with actual distance. You can change one and the other will update automatically. Not sure if that is what you are looking for.

Thanks! That's the best way of doing it :)

**Comment by taras-ko** [comment]
Back to the last item
> Add possibility to use signle objects for bridge generation.

What do you think on that?

**Comment by jeffmd** [comment]
+1.

**Comment by jeffmd** [comment]
I modified your current pull request, which just got applied to master, to allow object selection if operation object selection enabled in the UI settings panel.  Also modified your code so its not per operation ie hide all other paths, its now in the UI settings panel.  Still playing with the layout of the UI settings panel and will post a pic when done.

**Comment by ksuprynowicz** [comment]
> What do you think about this?

It would be very practical.
