### ISSUE TITLE
Problem trying to save toolpath using Shopbot MTC postprocessor

### ISSUE THREAD

**Issue by skovholt** [vilemduha/blendercam#89]
Hello, 

using latest blendercam from github trying to save a toolpath using the Shopbot MTC postprocessor i get an error. Saving using Iso works fine. 

See attached picture.

![2016-09-19 11_45_52-greenshot](https://cloud.githubusercontent.com/assets/8075211/18628402/57f1d006-7e60-11e6-9441-2113d19b9788.png)

update: 
reading trough previous issues, I found this mentioned in https://github.com/vilemnovak/blendercam/issues/22  (NC library outdated #22) as already being a known issue.

**Comment by jeffmd** [comment]
The shopbot MTC post processor needs to be fixed.  I ran into the same problem when updating the NC library.

**Comment by vilemnovak** [comment]
We should probably sync the nc library with the Heekscad project where it comes from. Not sure if we have anybody to do it now.

**Comment by pppalain** [comment]
heekscnc has not been updated in 9 years
