### ISSUE TITLE
tag 0.9 release please

### ISSUE THREAD

**Issue by greyltc** [vilemduha/blendercam#91]
Hi,
It looks like 0.9 is out:
http://blendercam.blogspot.co.uk/

Could you please tag the release appropriately here so that I know what code is stable?

Thanks!

**Comment by vilemnovak** [comment]
sorry, we never tagged, we rather make downloadable packages... I actually don't know how to tag :) Maybe I find out, but it should be with next versin.

**Comment by greyltc** [comment]
It's super easy!
1. Choose a commit that you'd like to mark as stable and note down its commit hash
2. Visit https://github.com/vilemnovak/blendercam/releases
3. Click the `Target:master` button and paste in your commit hash from step 1
4. Specify a version
5. Optionally fill in the rest of the info
6. Click the `Publish release` button

**Comment by pppalain** [comment]
still not tagged
