### ISSUE TITLE
No BlenderCAM mode?

### ISSUE THREAD

**Issue by HexValid** [vilemduha/blendercam#98]
Hi,
I am using BlenderCAM 0.9 linux amd64 binary on Arch Linux x86.
I cant see any BlenderCAM mode in Blender.
Is official binary broken?
[![image](http://i.hizliresim.com/V0vq7V.png)](http://hizliresim.com/V0vq7V)
Thanks,

**Comment by narvf** [comment]
Do you have installed numpy and shapely?

2017-03-15 11:26 GMT+01:00 Erkan Erdem <notifications@github.com>:

**Comment by HexValid** [comment]
Its worked after installed python-shapely package. Thanks.
